# metabuild.Dockerfile - Adds METABUILD source (can use core OR multi as base)
FROM alpine:latest

# Copy METABUILD source
COPY . /metabuild

# Add version
ARG VERSION
RUN test -n "$VERSION" && printf 'METABUILD %s\n' "$VERSION" > /metabuild/VERSION

# Create bootstrap entrypoint script
RUN mv /metabuild/entrypoint.sh /bin/metabuild


ENTRYPOINT ["/bin/metabuild"]
