# Dockerfile.lite - Adds METABUILD source
FROM ghcr.io/frinknet/metabuild-core:latest

# Copy METABUILD source
COPY . /metabuild

# Add version
ARG VERSION
RUN test -n "$VERSION" && printf 'METABUILD %s\n' "$VERSION" > /metabuild/VERSION

# Create bootstrap entrypoint script
RUN mv /metabuild/entrypoint.sh /bin/metabuild


ENTRYPOINT ["/bin/metabuild"]
