# metabuild.Dockerfile - Adds METABUILD source (can use core OR multi as base)
ARG BASE_IMAGE=ghcr.io/frinknet/metabuild:latest
FROM ${BASE_IMAGE}

# Copy METABUILD source
COPY . /metabuild

# Create bootstrap entrypoint script
RUN ln /metabuild/entrypoint.sh /bin/metabuild

ENTRYPOINT ["/bin/metabuild"]
